name: moler_qdx
channels:
  - rdkit
  - conda-forge
dependencies:
  - pip
  - python=3.10
  - rdkit
  - tensorflow
  # openbabel from conda + python bindings (separate) needed for plip
  - openbabel
  - pip:
    # fetch our talo fork of MSO, master branch, latest commit
    - mso:
      - git+https://github.com/talo/mso.git@master
    - numpy
    # this won't work cuz openbabel is a wonderful piece of software
    # - openbabel
    # but this works!
    - pybel
    # this also wont work as it will check for pip-installed openbabel
    # instead, clone the plip repo from github, go to setup.py & comment out openbabel under install_requires,
    # then do python3 setup.py install, this will work as long as you already have openbabel working via a separate method (not pip)
    # - plip
    - alphaspace2
    - loguru
    - tqdm
    - pandas
    # to read prelude excel file with pandas
    - openpyxl
    # to visualize generated mols as a grid
    - mols2grid
